// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bind.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createBindCode = `-- name: CreateBindCode :one
INSERT INTO channel_identity_bind_codes (id, token, issued_by_user_id, channel_type, expires_at)
VALUES (
  lower(hex(randomblob(4))) || '-' ||
  lower(hex(randomblob(2))) || '-' ||
  '4' || substr(lower(hex(randomblob(2))), 2) || '-' ||
  substr('89ab', abs(random()) % 4 + 1, 1) || substr(lower(hex(randomblob(2))), 2) || '-' ||
  lower(hex(randomblob(6))),
  ?1,
  ?2,
  ?3,
  ?4
)
RETURNING id, token, issued_by_user_id, channel_type, expires_at, used_at, used_by_channel_identity_id, created_at
`

type CreateBindCodeParams struct {
	Token          string         `json:"token"`
	IssuedByUserID string         `json:"issued_by_user_id"`
	ChannelType    sql.NullString `json:"channel_type"`
	ExpiresAt      sql.NullString `json:"expires_at"`
}

func (q *Queries) CreateBindCode(ctx context.Context, arg CreateBindCodeParams) (ChannelIdentityBindCode, error) {
	row := q.db.QueryRowContext(ctx, createBindCode,
		arg.Token,
		arg.IssuedByUserID,
		arg.ChannelType,
		arg.ExpiresAt,
	)
	var i ChannelIdentityBindCode
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IssuedByUserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedByChannelIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const getBindCode = `-- name: GetBindCode :one
SELECT id, token, issued_by_user_id, channel_type, expires_at, used_at, used_by_channel_identity_id, created_at
FROM channel_identity_bind_codes
WHERE token = ?1
`

func (q *Queries) GetBindCode(ctx context.Context, token string) (ChannelIdentityBindCode, error) {
	row := q.db.QueryRowContext(ctx, getBindCode, token)
	var i ChannelIdentityBindCode
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IssuedByUserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedByChannelIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const getBindCodeForUpdate = `-- name: GetBindCodeForUpdate :one
SELECT id, token, issued_by_user_id, channel_type, expires_at, used_at, used_by_channel_identity_id, created_at
FROM channel_identity_bind_codes
WHERE token = ?1
`

func (q *Queries) GetBindCodeForUpdate(ctx context.Context, token string) (ChannelIdentityBindCode, error) {
	row := q.db.QueryRowContext(ctx, getBindCodeForUpdate, token)
	var i ChannelIdentityBindCode
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IssuedByUserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedByChannelIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const markBindCodeUsed = `-- name: MarkBindCodeUsed :one
UPDATE channel_identity_bind_codes
SET used_at = CURRENT_TIMESTAMP, used_by_channel_identity_id = ?1
WHERE id = ?2
  AND used_at IS NULL
RETURNING id, token, issued_by_user_id, channel_type, expires_at, used_at, used_by_channel_identity_id, created_at
`

type MarkBindCodeUsedParams struct {
	UsedByChannelIdentityID sql.NullString `json:"used_by_channel_identity_id"`
	ID                      string         `json:"id"`
}

func (q *Queries) MarkBindCodeUsed(ctx context.Context, arg MarkBindCodeUsedParams) (ChannelIdentityBindCode, error) {
	row := q.db.QueryRowContext(ctx, markBindCodeUsed, arg.UsedByChannelIdentityID, arg.ID)
	var i ChannelIdentityBindCode
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.IssuedByUserID,
		&i.ChannelType,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedByChannelIdentityID,
		&i.CreatedAt,
	)
	return i, err
}
