// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: settings.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteSettingsByBotID = `-- name: DeleteSettingsByBotID :exec
UPDATE bots
SET language = 'auto',
    reasoning_enabled = false,
    reasoning_effort = 'medium',
    heartbeat_enabled = false,
    heartbeat_interval = 30,
    heartbeat_prompt = '',
    compaction_enabled = false,
    compaction_threshold = 100000,
    compaction_ratio = 80,
    chat_model_id = NULL,
    heartbeat_model_id = NULL,
    compaction_model_id = NULL,
    title_model_id = NULL,
    image_model_id = NULL,
    search_provider_id = NULL,
    memory_provider_id = NULL,
    tts_model_id = NULL,
    transcription_model_id = NULL,
    browser_context_id = NULL,
    persist_full_tool_results = false,
    show_tool_calls_in_im = false,
    tool_approval_config = '{"enabled":false,"write":{"require_approval":true,"bypass_globs":["/data/**","/tmp/**"],"force_review_globs":[]},"edit":{"require_approval":true,"bypass_globs":["/data/**","/tmp/**"],"force_review_globs":[]},"exec":{"require_approval":false,"bypass_commands":[],"force_review_commands":[]}}',
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
`

func (q *Queries) DeleteSettingsByBotID(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSettingsByBotID, id)
	return err
}

const getSettingsByBotID = `-- name: GetSettingsByBotID :one
SELECT
  bots.id AS bot_id,
  bots.language,
  bots.reasoning_enabled,
  bots.reasoning_effort,
  bots.heartbeat_enabled,
  bots.heartbeat_interval,
  bots.heartbeat_prompt,
  bots.compaction_enabled,
  bots.compaction_threshold,
  bots.compaction_ratio,
  bots.timezone,
  chat_models.id AS chat_model_id,
  heartbeat_models.id AS heartbeat_model_id,
  compaction_models.id AS compaction_model_id,
  title_models.id AS title_model_id,
  search_providers.id AS search_provider_id,
  memory_providers.id AS memory_provider_id,
  image_models.id AS image_model_id,
  tts_models.id AS tts_model_id,
  transcription_models.id AS transcription_model_id,
  browser_contexts.id AS browser_context_id,
  bots.persist_full_tool_results,
  bots.show_tool_calls_in_im,
  bots.tool_approval_config
FROM bots
LEFT JOIN models AS chat_models ON chat_models.id = bots.chat_model_id
LEFT JOIN models AS heartbeat_models ON heartbeat_models.id = bots.heartbeat_model_id
LEFT JOIN models AS compaction_models ON compaction_models.id = bots.compaction_model_id
LEFT JOIN models AS title_models ON title_models.id = bots.title_model_id
LEFT JOIN models AS image_models ON image_models.id = bots.image_model_id
LEFT JOIN search_providers ON search_providers.id = bots.search_provider_id
LEFT JOIN memory_providers ON memory_providers.id = bots.memory_provider_id
LEFT JOIN models AS tts_models ON tts_models.id = bots.tts_model_id
LEFT JOIN models AS transcription_models ON transcription_models.id = bots.transcription_model_id
LEFT JOIN browser_contexts ON browser_contexts.id = bots.browser_context_id
WHERE bots.id = ?1
`

type GetSettingsByBotIDRow struct {
	BotID                  string         `json:"bot_id"`
	Language               string         `json:"language"`
	ReasoningEnabled       int64          `json:"reasoning_enabled"`
	ReasoningEffort        string         `json:"reasoning_effort"`
	HeartbeatEnabled       int64          `json:"heartbeat_enabled"`
	HeartbeatInterval      int64          `json:"heartbeat_interval"`
	HeartbeatPrompt        string         `json:"heartbeat_prompt"`
	CompactionEnabled      int64          `json:"compaction_enabled"`
	CompactionThreshold    int64          `json:"compaction_threshold"`
	CompactionRatio        int64          `json:"compaction_ratio"`
	Timezone               sql.NullString `json:"timezone"`
	ChatModelID            sql.NullString `json:"chat_model_id"`
	HeartbeatModelID       sql.NullString `json:"heartbeat_model_id"`
	CompactionModelID      sql.NullString `json:"compaction_model_id"`
	TitleModelID           sql.NullString `json:"title_model_id"`
	SearchProviderID       sql.NullString `json:"search_provider_id"`
	MemoryProviderID       sql.NullString `json:"memory_provider_id"`
	ImageModelID           sql.NullString `json:"image_model_id"`
	TtsModelID             sql.NullString `json:"tts_model_id"`
	TranscriptionModelID   sql.NullString `json:"transcription_model_id"`
	BrowserContextID       sql.NullString `json:"browser_context_id"`
	PersistFullToolResults int64          `json:"persist_full_tool_results"`
	ShowToolCallsInIm      int64          `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     string         `json:"tool_approval_config"`
}

func (q *Queries) GetSettingsByBotID(ctx context.Context, id string) (GetSettingsByBotIDRow, error) {
	row := q.db.QueryRowContext(ctx, getSettingsByBotID, id)
	var i GetSettingsByBotIDRow
	err := row.Scan(
		&i.BotID,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.Timezone,
		&i.ChatModelID,
		&i.HeartbeatModelID,
		&i.CompactionModelID,
		&i.TitleModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.ImageModelID,
		&i.TtsModelID,
		&i.TranscriptionModelID,
		&i.BrowserContextID,
		&i.PersistFullToolResults,
		&i.ShowToolCallsInIm,
		&i.ToolApprovalConfig,
	)
	return i, err
}

const upsertBotSettings = `-- name: UpsertBotSettings :one
UPDATE bots
SET language = ?1,
    reasoning_enabled = ?2,
    reasoning_effort = ?3,
    heartbeat_enabled = ?4,
    heartbeat_interval = ?5,
    heartbeat_prompt = ?6,
    compaction_enabled = ?7,
    compaction_threshold = ?8,
    compaction_ratio = ?9,
    timezone = COALESCE(?10, bots.timezone),
    chat_model_id = COALESCE(?11, bots.chat_model_id),
    heartbeat_model_id = COALESCE(?12, bots.heartbeat_model_id),
    compaction_model_id = COALESCE(?13, bots.compaction_model_id),
    title_model_id = COALESCE(?14, bots.title_model_id),
    search_provider_id = COALESCE(?15, bots.search_provider_id),
    memory_provider_id = COALESCE(?16, bots.memory_provider_id),
    image_model_id = COALESCE(?17, bots.image_model_id),
    tts_model_id = COALESCE(?18, bots.tts_model_id),
    transcription_model_id = COALESCE(?19, bots.transcription_model_id),
    browser_context_id = COALESCE(?20, bots.browser_context_id),
    persist_full_tool_results = ?21,
    show_tool_calls_in_im = ?22,
    tool_approval_config = ?23,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?24
RETURNING
  id AS bot_id,
  language,
  reasoning_enabled,
  reasoning_effort,
  heartbeat_enabled,
  heartbeat_interval,
  heartbeat_prompt,
  compaction_enabled,
  compaction_threshold,
  compaction_ratio,
  timezone,
  chat_model_id,
  heartbeat_model_id,
  compaction_model_id,
  title_model_id,
  search_provider_id,
  memory_provider_id,
  image_model_id,
  tts_model_id,
  transcription_model_id,
  browser_context_id,
  persist_full_tool_results,
  show_tool_calls_in_im,
  tool_approval_config
`

type UpsertBotSettingsParams struct {
	Language               string         `json:"language"`
	ReasoningEnabled       int64          `json:"reasoning_enabled"`
	ReasoningEffort        string         `json:"reasoning_effort"`
	HeartbeatEnabled       int64          `json:"heartbeat_enabled"`
	HeartbeatInterval      int64          `json:"heartbeat_interval"`
	HeartbeatPrompt        string         `json:"heartbeat_prompt"`
	CompactionEnabled      int64          `json:"compaction_enabled"`
	CompactionThreshold    int64          `json:"compaction_threshold"`
	CompactionRatio        int64          `json:"compaction_ratio"`
	Timezone               sql.NullString `json:"timezone"`
	ChatModelID            sql.NullString `json:"chat_model_id"`
	HeartbeatModelID       sql.NullString `json:"heartbeat_model_id"`
	CompactionModelID      sql.NullString `json:"compaction_model_id"`
	TitleModelID           sql.NullString `json:"title_model_id"`
	SearchProviderID       sql.NullString `json:"search_provider_id"`
	MemoryProviderID       sql.NullString `json:"memory_provider_id"`
	ImageModelID           sql.NullString `json:"image_model_id"`
	TtsModelID             sql.NullString `json:"tts_model_id"`
	TranscriptionModelID   sql.NullString `json:"transcription_model_id"`
	BrowserContextID       sql.NullString `json:"browser_context_id"`
	PersistFullToolResults int64          `json:"persist_full_tool_results"`
	ShowToolCallsInIm      int64          `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     string         `json:"tool_approval_config"`
	ID                     string         `json:"id"`
}

type UpsertBotSettingsRow struct {
	ID                     string         `json:"id"`
	Language               string         `json:"language"`
	ReasoningEnabled       int64          `json:"reasoning_enabled"`
	ReasoningEffort        string         `json:"reasoning_effort"`
	HeartbeatEnabled       int64          `json:"heartbeat_enabled"`
	HeartbeatInterval      int64          `json:"heartbeat_interval"`
	HeartbeatPrompt        string         `json:"heartbeat_prompt"`
	CompactionEnabled      int64          `json:"compaction_enabled"`
	CompactionThreshold    int64          `json:"compaction_threshold"`
	CompactionRatio        int64          `json:"compaction_ratio"`
	Timezone               sql.NullString `json:"timezone"`
	ChatModelID            sql.NullString `json:"chat_model_id"`
	HeartbeatModelID       sql.NullString `json:"heartbeat_model_id"`
	CompactionModelID      sql.NullString `json:"compaction_model_id"`
	TitleModelID           sql.NullString `json:"title_model_id"`
	SearchProviderID       sql.NullString `json:"search_provider_id"`
	MemoryProviderID       sql.NullString `json:"memory_provider_id"`
	ImageModelID           sql.NullString `json:"image_model_id"`
	TtsModelID             sql.NullString `json:"tts_model_id"`
	TranscriptionModelID   sql.NullString `json:"transcription_model_id"`
	BrowserContextID       sql.NullString `json:"browser_context_id"`
	PersistFullToolResults int64          `json:"persist_full_tool_results"`
	ShowToolCallsInIm      int64          `json:"show_tool_calls_in_im"`
	ToolApprovalConfig     string         `json:"tool_approval_config"`
}

func (q *Queries) UpsertBotSettings(ctx context.Context, arg UpsertBotSettingsParams) (UpsertBotSettingsRow, error) {
	row := q.db.QueryRowContext(ctx, upsertBotSettings,
		arg.Language,
		arg.ReasoningEnabled,
		arg.ReasoningEffort,
		arg.HeartbeatEnabled,
		arg.HeartbeatInterval,
		arg.HeartbeatPrompt,
		arg.CompactionEnabled,
		arg.CompactionThreshold,
		arg.CompactionRatio,
		arg.Timezone,
		arg.ChatModelID,
		arg.HeartbeatModelID,
		arg.CompactionModelID,
		arg.TitleModelID,
		arg.SearchProviderID,
		arg.MemoryProviderID,
		arg.ImageModelID,
		arg.TtsModelID,
		arg.TranscriptionModelID,
		arg.BrowserContextID,
		arg.PersistFullToolResults,
		arg.ShowToolCallsInIm,
		arg.ToolApprovalConfig,
		arg.ID,
	)
	var i UpsertBotSettingsRow
	err := row.Scan(
		&i.ID,
		&i.Language,
		&i.ReasoningEnabled,
		&i.ReasoningEffort,
		&i.HeartbeatEnabled,
		&i.HeartbeatInterval,
		&i.HeartbeatPrompt,
		&i.CompactionEnabled,
		&i.CompactionThreshold,
		&i.CompactionRatio,
		&i.Timezone,
		&i.ChatModelID,
		&i.HeartbeatModelID,
		&i.CompactionModelID,
		&i.TitleModelID,
		&i.SearchProviderID,
		&i.MemoryProviderID,
		&i.ImageModelID,
		&i.TtsModelID,
		&i.TranscriptionModelID,
		&i.BrowserContextID,
		&i.PersistFullToolResults,
		&i.ShowToolCallsInIm,
		&i.ToolApprovalConfig,
	)
	return i, err
}
