services:
  postgres:
    image: memoh.cn/library/postgres:18-alpine
  qdrant:
    image: memoh.cn/qdrant/qdrant:latest
  migrate:
    image: memoh.cn/memohai/server:latest
  server:
    image: memoh.cn/memohai/server:latest
  web:
    image: memoh.cn/memohai/web:latest
  browser:
    image: memoh.cn/memohai/browser:${BROWSER_TAG:-latest}
  sparse:
    image: memoh.cn/memohai/sparse:latest
